services:
  injector-phishing:
    image: openaev/injector-phishing:latest
    ports:
      - "8080:8080"
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - OPENAEV_TENANT_ID=${OPENAEV_TENANT_ID}
      - INJECTOR_ID=${INJECTOR_ID}
      - INJECTOR_NAME=${INJECTOR_NAME}
      - INJECTOR_LOG_LEVEL=${INJECTOR_LOG_LEVEL}
      - PHISHING_PUBLIC_URL=${PHISHING_PUBLIC_URL}
      - PHISHING_SMTP_HOST=${PHISHING_SMTP_HOST}
      - PHISHING_MAIL_FROM=${PHISHING_MAIL_FROM}
    restart: always
