version: '3'
services:
  injector-mailer:
    image: openbas/injector-mailer:4.0.0
    environment:
      - OPENBAS_URL=http://localhost
      - OPENBAS_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - INJECTOR_NAME=Mailer
      - INJECTOR_LOG_LEVEL=error
    restart: always
