[project]
name = "openaev-email-smtp-injector"
version = "3.261009.0"
description = "An injector for crafting and sending emails over SMTP"
readme = "README.md"
authors = [
    { name = "Filigran", email = "contact@filigran.io" },
]
license = "Apache-2.0"
requires-python = ">=3.11,<4.0"

[tool.poetry.dependencies]
python = "^3.11"
pyoaev = "3.261009.0"
injector_common = { path = "../injector_common", develop = true }
pydantic = "^2.11.3"
pydantic-settings = "^2.11.0"
ioc-finder = "^9.4.1"

[tool.poetry.group.dev.dependencies]
black = "^26.3.0"
flake8 = "^7.3.0"
isort = "^8.0.1"
mypy = "^1.17.1"
pip-audit = "^2.9.0"
pre-commit = "^4.6.0"
ruff = "^0.14.13"
types-requests = "^2.32"
ty = "^0.0.56"

[tool.poetry.group.test.dependencies]
coverage = "^7.13.5"
pytest = "^9.1.1"
polyfactory = "^2.22.2"

[project.urls]
Homepage = "https://filigran.io/"
Repository = "https://github.com/OpenAEV-Platform/injectors/tree/main/email-smtp"
Documentation = "https://github.com/OpenAEV-Platform/injectors/tree/main/email-smtp/README.md"
Issues = "https://github.com/OpenAEV-Platform/injectors/issues"

[project.scripts]
EmailSMTPInjector = "email_smtp.__main__:main"

[tool.poetry]
packages = [
    { include = "email_smtp" },
]

[tool.isort]
profile = "black"
src_paths = [
    "email_smtp",
    "tests",
]

[tool.pytest.ini_options]
testpaths = [
    "./tests",
]

[tool.cmw]
install-command = "poetry install"
config-dump-command = "poetry run python -m email_smtp --dump-config-schema"
icon-path = "email_smtp/img/icon-email-smtp.png"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
