[project]
name = "openaev-stratus-injector"
version = "3.261009.0"
description = "An injector for emulating cloud attacks (AWS, Azure, Entra ID, GCP, Kubernetes, EKS) via Stratus Red Team"
license = "Apache-2.0"
readme = "README.md"
authors = [
    { name = "Filigran", email = "contact@filigran.io" },
]
requires-python = ">=3.11,<4.0"

[tool.poetry.dependencies]
python = "^3.11"
pyoaev = "3.261009.0"
injector_common = { path = "../injector_common", develop = true }
pydantic = "^2.11.3"

[tool.poetry.group.dev.dependencies]
black = "^26.3.0"
flake8 = "^7.3.0"
isort = "^8.0.1"
mypy = "^1.17.1"
pip-audit = "^2.9.0"
pre-commit = "^4.6.0"
ruff = "^0.14.13"
types-requests = "^2.32"
types-PyYAML = "^6.0.12"

[tool.poetry.group.test.dependencies]
coverage = "^7.13.5"
pytest = "^9.1.1"
polyfactory = "^2.22.2"

[tool.poetry]
packages = [
    { include = "stratus" },
]

[tool.isort]
profile = "black"
known_local_folder = [
    "stratus",
]

[tool.cmw]
install-command = "poetry install"
config-dump-command = "poetry run python -m stratus.openaev_stratus --dump-config-schema"
icon-path = "stratus/img/icon-stratus.png"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
