services:
  injector-nuclei:
    image: openaev/injector-nuclei:latest
    environment:
      - OPENAEV_URL=${OPENAEV_URL}
      - OPENAEV_TOKEN=${OPENAEV_TOKEN}
      - OPENAEV_TENANT_ID=${OPENAEV_TENANT_ID}
      - INJECTOR_ID=${INJECTOR_ID}
      - INJECTOR_NAME=${INJECTOR_NAME}
      - INJECTOR_LOG_LEVEL=${INJECTOR_LOG_LEVEL}
      - NUCLEI_SCAN_STRATEGY=${NUCLEI_SCAN_STRATEGY}
      - NUCLEI_TEMPLATES_PARALLELISM=${NUCLEI_TEMPLATES_PARALLELISM}
      - NUCLEI_HOSTS_PARALLELISM_PER_TEMPLATE=${NUCLEI_HOSTS_PARALLELISM_PER_TEMPLATE}
      - NUCLEI_MAX_REQUESTS_PER_SECOND=${NUCLEI_MAX_REQUESTS_PER_SECOND}
      - NUCLEI_TIMEOUT=${NUCLEI_TIMEOUT}
      - NUCLEI_RETRIES=${NUCLEI_RETRIES}
      - NUCLEI_MAX_HOST_ERROR=${NUCLEI_MAX_HOST_ERROR}
      - NUCLEI_RESPONSE_SIZE_READ=${NUCLEI_RESPONSE_SIZE_READ}
      - NUCLEI_RESPONSE_SIZE_SAVE=${NUCLEI_NUCLEI_RESPONSE_SIZE_SAVE}
      - NUCLEI_EXCLUDE_TYPE=${NUCLEI_EXCLUDE_TYPE}
      - NUCLEI_EXCLUDE_SEVERITY=${NUCLEI_EXCLUDE_SEVERITY}
    restart: always
