[project]
name = "openaev-email-gws-injector"
version = "3.261009.0"
description = "An injector for sending emails through Google Workspace (Gmail API)"
readme = "README.md"
authors = [
    { name = "Filigran", email = "contact@filigran.io" },
]
license = "Apache-2.0"
requires-python = ">=3.11,<4.0"

[tool.poetry.dependencies]
python = "^3.11"
pyoaev = "3.261009.0"
injector_common = { path = "../injector_common", develop = true }
requests = "^2.33"
google-auth = "^2.35"
pydantic = "^2.11.3"
pydantic-settings = "^2.11.0"

[tool.poetry.group.dev.dependencies]
black = "^26.3.0"
flake8 = "^7.3.0"
isort = "^8.0.1"
mypy = "^1.17.1"
pip-audit = "^2.9.0"
pre-commit = "^4.6.0"
ruff = "^0.14.13"
types-requests = "^2.32"

[tool.poetry.group.test.dependencies]
coverage = "^7.13.5"
pytest = "^9.1.1"
polyfactory = "^2.22.2"

[tool.poetry]
packages = [
    { include = "email_gws_injector" },
]

[tool.isort]
profile = "black"
known_local_folder = [
    "email_gws_injector",
]

[tool.cmw]
install-command = "poetry install"
config-dump-command = "poetry run python -m email_gws_injector.openaev_email_gws --dump-config-schema"
icon-path = "email_gws_injector/img/icon-email-google-workspace.png"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
